spring:
  profiles:
    active: '@activeProfiles@'
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    host: ${env.REDIS_HOST}
    port: ${env.REDIS_PORT}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: ${env.SERVER_PORT:8080}

cluedohelper:
  http:
    auth-token-header-name: X-API-Key
    auth-token: ${env.AUTH_TOKEN}

app:
  version: '@revision@'
