management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

logging:
  level:
    root: ERROR
    org.springframework: INFO
    com.perso.cluedohelper: TRACE
    ExternalRequest: TRACE
  config: classpath:log4j/log4j2-local.yml
